import json

RULES_PATH = "/home/rubengaona/bots/bot_multi_jobs/config/rules.json"

mega_dict = [
    # --- PROGRAMMING LANGUAGES ---
    ["C", ["\\bc\\b", "lenguaje c"]],
    ["C++", ["c\\+\\+", "cpp"]],
    ["C#", ["c#", "c-sharp", "csharp"]],
    ["Java", ["\\bjava\\b"]],
    ["Python", ["python", "python3"]],
    ["Ruby", ["\\bruby\\b", "ruby on rails"]],
    ["PHP", ["\\bphp\\b", "php7", "php8"]],
    ["JavaScript", ["javascript", "js", "ecmascript", "es6"]],
    ["TypeScript", ["typescript", "ts"]],
    ["Go", ["\\bgo\\b", "golang"]],
    ["Rust", ["\\brust\\b", "rustlang"]],
    ["Swift", ["\\bswift\\b", "swiftui"]],
    ["Kotlin", ["\\bkotlin\\b"]],
    ["Objective-C", ["objective-c", "obj-c"]],
    ["Dart", ["\\bdart\\b"]],
    ["R", ["\\br\\b", "r-language", "lenguaje r"]],
    ["MATLAB", ["matlab"]],
    ["Scala", ["\\bscala\\b"]],
    ["Perl", ["\\bperl\\b"]],
    ["Haskell", ["haskell"]],
    ["Lua", ["\\blua\\b"]],
    ["HTML/CSS", ["html", "html5", "css", "css3"]],
    ["Bash/Shell", ["bash", "shell script", "shell scripting", "sh", "zsh"]],
    ["PowerShell", ["powershell", "pwsh"]],
    ["Groovy", ["groovy"]],
    ["Elixir", ["elixir"]],
    ["Erlang", ["erlang"]],
    ["Clojure", ["clojure"]],
    ["F#", ["f#", "fsharp"]],
    ["Julia", ["julia"]],
    ["COBOL", ["cobol"]],
    ["Fortran", ["fortran"]],
    ["ABAP", ["abap", "sap abap"]],
    ["Apex", ["apex", "salesforce apex"]],
    ["Solidity", ["solidity", "smart contracts"]],
    ["WebAssembly", ["webassembly", "wasm"]],
    # --- FRONTEND & UI ---
    ["React", ["react", "reactjs", "react.js"]],
    ["Angular", ["angular", "angularjs", "angular.js", "angular 2+"]],
    ["Vue.js", ["vue", "vuejs", "vue.js", "vue3"]],
    ["Svelte", ["svelte", "sveltekit"]],
    ["Ember.js", ["ember", "ember.js"]],
    ["Backbone.js", ["backbone", "backbone.js"]],
    ["Next.js", ["nextjs", "next.js", "next js"]],
    ["Nuxt.js", ["nuxtjs", "nuxt.js", "nuxt"]],
    ["Gatsby", ["gatsby", "gatsbyjs"]],
    ["Remix", ["remix", "remix run"]],
    ["Astro", ["astro", "astrojs"]],
    ["Tailwind CSS", ["tailwind", "tailwindcss", "tailwind css"]],
    ["Bootstrap", ["bootstrap"]],
    ["Material UI", ["material ui", "mui", "material-ui"]],
    ["Chakra UI", ["chakra ui", "chakra-ui"]],
    ["Ant Design", ["ant design", "antd"]],
    ["Bulma", ["bulma"]],
    ["Sass/SCSS", ["sass", "scss"]],
    ["LESS", ["\\bless\\b"]],
    ["Webpack", ["webpack"]],
    ["Rollup", ["rollup"]],
    ["Vite", ["vite", "vitejs"]],
    ["Parcel", ["parcel", "parceljs"]],
    ["Babel", ["babel", "babeljs"]],
    ["ESLint", ["eslint"]],
    ["Prettier", ["prettier"]],
    # --- BACKEND & FRAMEWORKS ---
    ["Node.js", ["node", "nodejs", "node.js"]],
    ["Express", ["express", "expressjs", "express.js"]],
    ["NestJS", ["nestjs", "nest.js"]],
    ["Koa", ["koajs", "koa.js"]],
    ["Fastify", ["fastify"]],
    ["Django", ["django"]],
    ["Flask", ["flask"]],
    ["FastAPI", ["fastapi"]],
    ["Spring Boot", ["spring", "spring boot", "springboot"]],
    ["Hibernate", ["hibernate"]],
    ["ASP.NET", ["asp.net", "asp net"]],
    [".NET Core", [".net core", "dotnet core"]],
    ["Entity Framework", ["entity framework", "ef core"]],
    ["Laravel", ["laravel"]],
    ["Symfony", ["symfony"]],
    ["CodeIgniter", ["codeigniter"]],
    ["CakePHP", ["cakephp"]],
    ["Ruby on Rails", ["rails", "ruby on rails", "ror"]],
    ["Echo (Go)", ["echo framework", "go echo"]],
    ["Gin (Go)", ["gin framework", "go gin"]],
    ["Fiber (Go)", ["go fiber", "fiber framework"]],
    ["Phoenix", ["phoenix framework", "elixir phoenix"]],
    ["Ktor", ["ktor"]],
    ["Micronaut", ["micronaut"]],
    ["Quarkus", ["quarkus"]],
    ["Dropwizard", ["dropwizard"]],
    ["Play Framework", ["play framework"]],
    # --- MOBILE & DESKTOP ---
    ["React Native", ["react native", "react-native"]],
    ["Flutter", ["flutter"]],
    ["Xamarin", ["xamarin"]],
    ["MAUI", [".net maui", "maui"]],
    ["Ionic", ["ionic", "ionic framework"]],
    ["Cordova", ["cordova", "apache cordova"]],
    ["Capacitor", ["capacitor", "capacitorjs"]],
    ["Electron", ["electron", "electronjs"]],
    ["Tauri", ["tauri"]],
    ["Qt", ["\\bqt\\b", "qt5", "qt6"]],
    ["WPF", ["wpf", "windows presentation foundation"]],
    # --- DATABASES & STORAGE ---
    ["MySQL", ["mysql"]],
    ["PostgreSQL", ["postgresql", "postgres"]],
    ["MariaDB", ["mariadb"]],
    ["SQLite", ["sqlite", "sqlite3"]],
    ["Oracle DB", ["oracle", "oracle db", "oracle database"]],
    ["SQL Server", ["sql server", "mssql", "microsoft sql server"]],
    ["MongoDB", ["mongodb", "mongo"]],
    ["CouchDB", ["couchdb"]],
    ["Couchbase", ["couchbase"]],
    ["Cassandra", ["cassandra", "apache cassandra"]],
    ["ScyllaDB", ["scylladb"]],
    ["DynamoDB", ["dynamodb", "amazon dynamodb"]],
    ["Cosmos DB", ["cosmos db", "azure cosmos db"]],
    ["Firebase", ["firebase", "firestore"]],
    ["Supabase", ["supabase"]],
    ["Redis", ["redis"]],
    ["Memcached", ["memcached"]],
    ["Hazelcast", ["hazelcast"]],
    ["Neo4j", ["neo4j"]],
    ["ArangoDB", ["arangodb"]],
    ["Elasticsearch", ["elasticsearch", "elastic search"]],
    ["Solr", ["solr", "apache solr"]],
    ["OpenSearch", ["opensearch"]],
    ["InfluxDB", ["influxdb"]],
    ["TimescaleDB", ["timescaledb"]],
    ["ClickHouse", ["clickhouse"]],
    ["Snowflake", ["snowflake"]],
    ["Redshift", ["redshift", "amazon redshift"]],
    ["BigQuery", ["bigquery", "google bigquery"]],
    ["Databricks", ["databricks"]],
    # --- CLOUD, INFRA & DEVOPS ---
    ["AWS", ["aws", "amazon web services"]],
    ["Azure", ["azure", "microsoft azure"]],
    ["Google Cloud (GCP)", ["gcp", "google cloud", "google cloud platform"]],
    ["IBM Cloud", ["ibm cloud"]],
    ["Oracle Cloud (OCI)", ["oci", "oracle cloud"]],
    ["Alibaba Cloud", ["alibaba cloud", "aliyun"]],
    ["DigitalOcean", ["digitalocean", "digital ocean"]],
    ["Heroku", ["heroku"]],
    ["Vercel", ["vercel"]],
    ["Netlify", ["netlify"]],
    ["Docker", ["docker", "docker compose"]],
    ["Kubernetes", ["kubernetes", "k8s"]],
    ["Docker Swarm", ["docker swarm"]],
    ["Nomad", ["nomad", "hashicorp nomad"]],
    ["OpenShift", ["openshift", "red hat openshift"]],
    ["Rancher", ["rancher"]],
    ["Terraform", ["terraform", "hashicorp terraform"]],
    ["Ansible", ["ansible"]],
    ["Chef", ["chef", "chef infra"]],
    ["Puppet", ["puppet"]],
    ["SaltStack", ["saltstack", "salt"]],
    ["Pulumi", ["pulumi"]],
    ["Vagrant", ["vagrant"]],
    ["Packer", ["packer", "hashicorp packer"]],
    ["Jenkins", ["jenkins"]],
    ["GitLab CI", ["gitlab ci", "gitlab-ci"]],
    ["GitHub Actions", ["github actions"]],
    ["CircleCI", ["circleci"]],
    ["Travis CI", ["travis ci", "travis-ci"]],
    ["Bamboo", ["bamboo", "atlassian bamboo"]],
    ["TeamCity", ["teamcity"]],
    ["Argo CD", ["argo cd", "argocd"]],
    ["Flux", ["flux cd", "fluxcd"]],
    ["Istio", ["istio"]],
    ["Linkerd", ["linkerd"]],
    ["Consul", ["consul", "hashicorp consul"]],
    # --- DATA, ML & AI ---
    ["Pandas", ["pandas"]],
    ["NumPy", ["numpy"]],
    ["SciPy", ["scipy"]],
    ["Scikit-learn", ["scikit-learn", "sklearn"]],
    ["TensorFlow", ["tensorflow", "tf"]],
    ["PyTorch", ["pytorch", "torch"]],
    ["Keras", ["keras"]],
    ["XGBoost", ["xgboost"]],
    ["LightGBM", ["lightgbm"]],
    ["CatBoost", ["catboost"]],
    ["OpenCV", ["opencv", "cv2"]],
    ["NLTK", ["nltk"]],
    ["SpaCy", ["spacy"]],
    ["Hugging Face", ["hugging face", "huggingface", "transformers"]],
    ["LangChain", ["langchain"]],
    ["LlamaIndex", ["llamaindex", "llama-index"]],
    ["OpenAI", ["openai", "gpt-4", "gpt-3"]],
    ["Anthropic", ["anthropic", "claude"]],
    ["Gemini", ["gemini", "google gemini"]],
    ["MLflow", ["mlflow"]],
    ["Kubeflow", ["kubeflow"]],
    ["DVC", ["dvc", "data version control"]],
    ["Apache Spark", ["spark", "apache spark", "pyspark"]],
    ["Hadoop", ["hadoop", "apache hadoop"]],
    ["Flink", ["flink", "apache flink"]],
    ["Kafka", ["kafka", "apache kafka"]],
    ["RabbitMQ", ["rabbitmq"]],
    ["ActiveMQ", ["activemq", "apache activemq"]],
    ["NATS", ["nats"]],
    ["Airflow", ["airflow", "apache airflow"]],
    ["Luigi", ["luigi"]],
    ["Prefect", ["prefect"]],
    ["Dagster", ["dagster"]],
    ["dbt", ["dbt", "data build tool"]],
    ["Talend", ["talend"]],
    ["Informatica", ["informatica"]],
    ["Alteryx", ["alteryx"]],
    # --- OBSERVABILITY & SECURITY ---
    ["Datadog", ["datadog"]],
    ["New Relic", ["new relic", "newrelic"]],
    ["AppDynamics", ["appdynamics"]],
    ["Dynatrace", ["dynatrace"]],
    ["Splunk", ["splunk"]],
    ["ELK Stack", ["elk", "elk stack", "elasticsearch logstash kibana"]],
    ["Logstash", ["logstash"]],
    ["Kibana", ["kibana"]],
    ["Grafana", ["grafana"]],
    ["Prometheus", ["prometheus"]],
    ["Jaeger", ["jaeger"]],
    ["Zipkin", ["zipkin"]],
    ["OpenTelemetry", ["opentelemetry", "otel"]],
    ["Sentry", ["sentry"]],
    ["SonarQube", ["sonarqube", "sonar qube"]],
    ["Fortify", ["fortify"]],
    ["Checkmarx", ["checkmarx"]],
    ["Trivy", ["trivy"]],
    ["Wireshark", ["wireshark"]],
    ["OAuth", ["oauth", "oauth2"]],
    ["OpenID Connect", ["openid connect", "oidc"]],
    ["SAML", ["saml", "saml2"]],
    ["JWT", ["jwt", "json web token"]],
    ["Keycloak", ["keycloak"]],
    ["Auth0", ["auth0"]],
    ["Okta", ["okta"]],
    ["Active Directory", ["active directory", "ad"]],
    # --- METHODOLOGIES, ARCHITECTURE & MISC ---
    ["Agile", ["agile", "metodologias agiles", "metodologías ágiles"]],
    ["Scrum", ["scrum"]],
    ["Kanban", ["kanban"]],
    ["SAFe", ["safe", "scaled agile framework"]],
    ["TDD", ["tdd", "test driven development", "test-driven development"]],
    ["BDD", ["bdd", "behavior driven development", "behavior-driven development"]],
    ["DDD", ["ddd", "domain driven design", "domain-driven design"]],
    ["CI/CD", ["ci/cd", "ci-cd", "continuous integration", "integracion continua"]],
    [
        "Microservices",
        ["microservices", "microservicios", "arquitectura de microservicios"],
    ],
    ["Serverless", ["serverless"]],
    ["REST", ["rest", "restful", "api rest"]],
    ["GraphQL", ["graphql"]],
    ["SOAP", ["soap"]],
    ["gRPC", ["grpc"]],
    ["WebSockets", ["websockets", "websocket"]],
    ["WebRTC", ["webrtc"]],
    ["MVC", ["mvc", "model view controller"]],
    ["SOLID", ["solid", "principios solid"]],
    ["Figma", ["figma"]],
    ["Sketch", ["sketch"]],
    ["Adobe XD", ["adobe xd"]],
    ["Jira", ["jira", "atlassian jira"]],
    ["Confluence", ["confluence"]],
    ["Trello", ["trello"]],
    ["Notion", ["notion"]],
]

with open(RULES_PATH, "r", encoding="utf-8") as f:
    rules = json.load(f)

# Convert existing list to a dictionary for easy merging
existing = {item[0]: set(item[1]) for item in rules.get("TECH_TOOLS_CATALOG", [])}

added_canonicals = 0
added_aliases = 0

for new_canonical, new_aliases in mega_dict:
    if new_canonical not in existing:
        existing[new_canonical] = set()
        added_canonicals += 1

    for alias in new_aliases:
        if alias not in existing[new_canonical]:
            existing[new_canonical].add(alias)
            added_aliases += 1

# Convert back to the list of lists format
final_catalog = [[canonical, list(aliases)] for canonical, aliases in existing.items()]

# Sort alphabetically by canonical name for cleanliness
final_catalog.sort(key=lambda x: x[0].lower())

rules["TECH_TOOLS_CATALOG"] = final_catalog

with open(RULES_PATH, "w", encoding="utf-8") as f:
    json.dump(rules, f, ensure_ascii=False, indent=2)

print("Mega-Dictionary injected successfully!")
print(f"Added {added_canonicals} entirely new technologies.")
print(f"Added {added_aliases} new search aliases/acronyms.")
print(f"Total technologies now in the brain: {len(final_catalog)}")
